/*
 * DO NOT MODIFY
 *
 * This file was generated by dtoc from a .dtb (device tree binary) file.
 */

/* Allow use of U_BOOT_DEVICE() in this file */
#define DT_PLATDATA_C

#include <common.h>
#include <dm.h>
#include <dt-structs.h>

/* Node /clock-controller@ff440000 index 0 */
static struct dtd_rockchip_rk3328_cru dtv_clock_controller_at_ff440000 = {
	.reg			= {0xff440000, 0x1000},
	.rockchip_grf		= 0x3b,
};
U_BOOT_DEVICE(clock_controller_at_ff440000) = {
	.name		= "rockchip_rk3328_cru",
	.platdata	= &dtv_clock_controller_at_ff440000,
	.platdata_size	= sizeof(dtv_clock_controller_at_ff440000),
	.parent_idx	= -1,
};

/* Node /dmc index 1 */
static struct dtd_rockchip_rk3328_dmc dtv_dmc = {
	.reg			= {0xff400000, 0x1000, 0xff780000, 0x3000, 0xff100000, 0x1000, 0xff440000, 0x1000,
		0xff720000, 0x1000, 0xff798000, 0x1000},
	.rockchip_sdram_params	= {0x1, 0xc, 0x3, 0x1, 0x0, 0x0, 0x10, 0x10,
		0x10, 0x10, 0x0, 0x98899459, 0x0, 0x2e, 0x544, 0x15,
		0x432, 0xff, 0x320, 0x6, 0x1, 0x0, 0x1, 0x0,
		0x43041008, 0x64, 0x300054, 0xd0, 0x500002, 0xd4, 0x10000, 0xd8,
		0xe03, 0xdc, 0x43001a, 0xe0, 0x10000, 0xe4, 0xe0005, 0xf4,
		0xf011f, 0x100, 0xb141b11, 0x104, 0x3031a, 0x108, 0x3060809, 0x10c,
		0x606000, 0x110, 0x8020409, 0x114, 0x1010606, 0x118, 0x2020004, 0x120,
		0x404, 0x138, 0x58, 0x180, 0x900024, 0x184, 0x1400000, 0x190,
		0x7050002, 0x198, 0x5001100, 0x1a0, 0xc0400003, 0x240, 0xa020b28, 0x244,
		0x101, 0x250, 0xf00, 0x490, 0x1, 0xffffffff, 0xffffffff, 0xffffffff,
		0xffffffff, 0xffffffff, 0xffffffff, 0x4, 0xb, 0x28, 0xc, 0x2c,
		0x0, 0x30, 0x6, 0xffffffff, 0xffffffff, 0x77, 0x88, 0x79,
		0x79, 0x87, 0x97, 0x87, 0x78, 0x77, 0x78, 0x87,
		0x88, 0x87, 0x87, 0x77, 0x78, 0x78, 0x78, 0x78,
		0x78, 0x78, 0x78, 0x78, 0x78, 0x69, 0x9, 0x77,
		0x78, 0x77, 0x78, 0x77, 0x78, 0x77, 0x78, 0x77,
		0x79, 0x9, 0x78, 0x78, 0x78, 0x78, 0x78, 0x78,
		0x78, 0x78, 0x78, 0x69, 0x9, 0x77, 0x78, 0x77,
		0x77, 0x77, 0x77, 0x77, 0x77, 0x77, 0x79, 0x9,
		0x78, 0x78, 0x78, 0x78, 0x78, 0x78, 0x78, 0x78,
		0x78, 0x69, 0x9, 0x77, 0x78, 0x77, 0x78, 0x77,
		0x78, 0x77, 0x78, 0x77, 0x79, 0x9, 0x78, 0x78,
		0x78, 0x78, 0x78, 0x78, 0x78, 0x78, 0x78, 0x69,
		0x9, 0x77, 0x78, 0x77, 0x77, 0x77, 0x77, 0x77,
		0x77, 0x77, 0x79, 0x9},
};
U_BOOT_DEVICE(dmc) = {
	.name		= "rockchip_rk3328_dmc",
	.platdata	= &dtv_dmc,
	.platdata_size	= sizeof(dtv_dmc),
	.parent_idx	= -1,
};

/* Node /pinctrl/gpio0@ff210000 index 2 */
static struct dtd_rockchip_gpio_bank dtv_gpio0_at_ff210000 = {
	.clocks			= {
			{0, {200}},},
	.gpio_controller	= true,
	.interrupt_controller	= true,
	.interrupts		= {0x0, 0x33, 0x4},
	.reg			= {0xff210000, 0x100},
};
U_BOOT_DEVICE(gpio0_at_ff210000) = {
	.name		= "rockchip_gpio_bank",
	.platdata	= &dtv_gpio0_at_ff210000,
	.platdata_size	= sizeof(dtv_gpio0_at_ff210000),
	.parent_idx	= 5,
};

/* Node /mmc@ff500000 index 3 */
static struct dtd_rockchip_rk3288_dw_mshc dtv_mmc_at_ff500000 = {
	.bus_width		= 0x4,
	.cap_mmc_highspeed	= true,
	.cap_sd_highspeed	= true,
	.clocks			= {
			{0, {317}},
			{0, {33}},
			{0, {74}},
			{0, {78}},},
	.disable_wp		= true,
	.fifo_depth		= 0x100,
	.interrupts		= {0x0, 0xc, 0x4},
	.max_frequency		= 0x8f0d180,
	.pinctrl_0		= {0x4a, 0x4b, 0x4c, 0x4d},
	.pinctrl_names		= "default",
	.reg			= {0xff500000, 0x4000},
	.u_boot_spl_fifo_mode	= true,
	.vmmc_supply		= 0x4e,
};
U_BOOT_DEVICE(mmc_at_ff500000) = {
	.name		= "rockchip_rk3288_dw_mshc",
	.platdata	= &dtv_mmc_at_ff500000,
	.platdata_size	= sizeof(dtv_mmc_at_ff500000),
	.parent_idx	= -1,
};

/* Node /mmc@ff520000 index 4 */
static struct dtd_rockchip_rk3288_dw_mshc dtv_mmc_at_ff520000 = {
	.bus_width		= 0x8,
	.cap_mmc_highspeed	= true,
	.clocks			= {
			{0, {319}},
			{0, {35}},
			{0, {76}},
			{0, {80}},},
	.fifo_depth		= 0x100,
	.interrupts		= {0x0, 0xe, 0x4},
	.max_frequency		= 0x8f0d180,
	.mmc_hs200_1_8v		= true,
	.non_removable		= true,
	.pinctrl_0		= {0x4f, 0x50, 0x51, 0x0},
	.pinctrl_names		= "default",
	.reg			= {0xff520000, 0x4000},
	.u_boot_spl_fifo_mode	= true,
	.vmmc_supply		= 0x1e,
	.vqmmc_supply		= 0x1f,
};
U_BOOT_DEVICE(mmc_at_ff520000) = {
	.name		= "rockchip_rk3288_dw_mshc",
	.platdata	= &dtv_mmc_at_ff520000,
	.platdata_size	= sizeof(dtv_mmc_at_ff520000),
	.parent_idx	= -1,
};

/* Node /pinctrl index 5 */
static struct dtd_rockchip_rk3328_pinctrl dtv_pinctrl = {
	.ranges			= true,
	.rockchip_grf		= 0x3b,
};
U_BOOT_DEVICE(pinctrl) = {
	.name		= "rockchip_rk3328_pinctrl",
	.platdata	= &dtv_pinctrl,
	.platdata_size	= sizeof(dtv_pinctrl),
	.parent_idx	= -1,
};

/* Node /sdmmc-regulator index 6 */
static struct dtd_regulator_fixed dtv_sdmmc_regulator = {
	.gpio			= {0x65, 0x1e, 0x1},
	.pinctrl_0		= 0x66,
	.pinctrl_names		= "default",
	.regulator_max_microvolt = 0x325aa0,
	.regulator_min_microvolt = 0x325aa0,
	.regulator_name		= "vcc_sd",
	.vin_supply		= 0x1e,
};
U_BOOT_DEVICE(sdmmc_regulator) = {
	.name		= "regulator_fixed",
	.platdata	= &dtv_sdmmc_regulator,
	.platdata_size	= sizeof(dtv_sdmmc_regulator),
	.parent_idx	= -1,
};

/* Node /serial@ff130000 index 7 */
static struct dtd_ns16550_serial dtv_serial_at_ff130000 = {
	.clock_frequency	= 0x16e3600,
	.clocks			= {
			{0, {40}},
			{0, {212}},},
	.dma_names		= {"tx", "rx"},
	.dmas			= {0x10, 0x6, 0x10, 0x7},
	.interrupts		= {0x0, 0x39, 0x4},
	.pinctrl_0		= 0x27,
	.pinctrl_names		= "default",
	.reg			= {0xff130000, 0x100},
	.reg_io_width		= 0x4,
	.reg_shift		= 0x2,
};
U_BOOT_DEVICE(serial_at_ff130000) = {
	.name		= "ns16550_serial",
	.platdata	= &dtv_serial_at_ff130000,
	.platdata_size	= sizeof(dtv_serial_at_ff130000),
	.parent_idx	= -1,
};

/* Node /spi@ff190000 index 8 */
static struct dtd_rockchip_rk3328_spi dtv_spi_at_ff190000 = {
	.clocks			= {
			{0, {32}},
			{0, {209}},},
	.dma_names		= {"tx", "rx"},
	.dmas			= {0x10, 0x8, 0x10, 0x9},
	.interrupts		= {0x0, 0x31, 0x4},
	.pinctrl_0		= {0x2f, 0x30, 0x31, 0x32},
	.pinctrl_names		= "default",
	.reg			= {0xff190000, 0x1000},
};
U_BOOT_DEVICE(spi_at_ff190000) = {
	.name		= "rockchip_rk3328_spi",
	.platdata	= &dtv_spi_at_ff190000,
	.platdata_size	= sizeof(dtv_spi_at_ff190000),
	.parent_idx	= -1,
};

/* Node /spi@ff190000/spiflash@0 index 9 */
static struct dtd_jedec_spi_nor dtv_spiflash_at_0 = {
	.reg			= {0x0, 0x0},
	.spi_max_frequency	= 0x2faf080,
};
U_BOOT_DEVICE(spiflash_at_0) = {
	.name		= "jedec_spi_nor",
	.platdata	= &dtv_spiflash_at_0,
	.platdata_size	= sizeof(dtv_spiflash_at_0),
	.parent_idx	= 8,
};

/* Node /syscon@ff100000 index 10 */
static struct dtd_rockchip_rk3328_grf dtv_syscon_at_ff100000 = {
	.reg			= {0xff100000, 0x1000},
};
U_BOOT_DEVICE(syscon_at_ff100000) = {
	.name		= "rockchip_rk3328_grf",
	.platdata	= &dtv_syscon_at_ff100000,
	.platdata_size	= sizeof(dtv_syscon_at_ff100000),
	.parent_idx	= -1,
};

void dm_populate_phandle_data(void) {
}
